enableInlineBuilds: true

lockfileFilename: public-yarn.lock

nodeLinker: node-modules

npmAuthToken: '${NPM_TOKEN}'

npmRegistryServer: 'https://registry.npmjs.org'

yarnPath: .yarn/releases/yarn-3.5.0.cjs
